In [7]:
import os
import importlib

# Change directory to AD_variant_analysis
os.chdir("AD_variant_analysis")

# List all Python files in the folder
modules = [f[:-3] for f in os.listdir() if f.endswith(".py")]

# Import all modules dynamically
for module in modules:
    globals()[module] = importlib.import_module(module)

First, you need a dataframe formatted as below with information on uniprotIDs, AD coordinates, DBD coordinates.

In [5]:
all_TFs = pd.read_csv("all_TFs_table_proteins_with_IDR.txt", sep="\t", index_col = 0)
all_TFs

,1,2,uniprotID,ENSG,ENST,DBD_coords,AD_coords,RD_coords,Bif_coords,length,IDR_coords
0,NaN,NaN,A0A087WUV0,NaN,ENST00000425953,"221-243,249-271,277-299,305-327,333-355,361-38...",NaN,NaN,NaN,1,"1-216,498-523"
1,NaN,NaN,A0AVK6,NaN,ENST00000250024,"114-182,262-347",NaN,NaN,NaN,1,"1-115,337-868"
2,NaN,NaN,A1YPR0,NaN,ENST00000535628,"364-386,392-414,420-442,448-469",NaN,NaN,NaN,1,"128-364,471-620"
3,NaN,NaN,A2RRD8,NaN,ENST00000391781,"161-183,189-211,217-239,245-267,273-295,301-32...",NaN,NaN,NaN,1,51-156
4,NaN,NaN,A2RU54,NaN,ENST00000339992,150-206,NaN,NaN,NaN,1,"1-158,224-274"
...,...,...,...,...,...,...,...,...,...,...,...
1585,NaN,NaN,Q9Y692,NaN,ENST00000294409,89-165,422-573,NaN,NaN,1,"1-90,183-258,348-574"
1586,NaN,NaN,Q9Y6Q3,NaN,ENST00000374227,"293-315,321-343,377-399,405-427,433-455,461-48...",NaN,NaN,NaN,1,"1-290,618-631"
1587,NaN,NaN,Q9Y6Q9,NaN,ENST00000371998,31-83,621-1424,NaN,NaN,1,"1-40,86-108,177-193,355-1425"
1588,NaN,NaN,Q9Y6X0,NaN,ENST00000649279,"583-596,1015-1027,1450-1462",NaN,NaN,NaN,1,"1-1400,1437-1597"
1589,NaN,NaN,Q9Y6Y1,NaN,ENST00000303635,69-182,"702-841,422-501",NaN,NaN,1,"1-55,245-863,993-1035,1171-1515,1644-1674"

Next, you need a bed file of variants as below.

In [6]:
variants = pd.read_csv("SFARI_TF_de_novo_variants_gpf.bed", sep="\t", header=None)
variants

      0          1          2  3  4  5
0     1   61352563   61352564  C  T  0
1     2    1917306    1917307  A  G  0
2     2  156329363  156329364  A  G  0
3     1   61352563   61352564  C  T  0
4     4  105234730  105234731  G  T  0
..   ..        ...        ... .. .. ..
112  18   55228884   55228885  G  A  0
113  18   55228993   55228994  G  A  0
114  21   38445460   38445461  G  C  0
115  22   42213188   42213189  C  T  0
116  22   42214836   42214837  T  C  0

[117 rows x 6 columns]

In [ ]:
! intersect-variants -c /Users/sanjanakotha/Desktop/Staller_Lab/variant_analysis/ -v SFARI_TF_de_novo_variants_gpf.bed -o /Users/sanjanakotha/Desktop/Staller_Lab/variant_analysis/output

zsh:1: command not found: intersect-variants